[env:waveshare_lcd_4_3B_LVGL9]
platform = espressif32
board = esp32-s3-devkitc1-n16r8
framework = espidf
board_build.sdkconfig = sdkconfig.waveshare_lcd_4_3B_LVGL9
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = default_16MB.csv
upload_speed=921600
monitor_speed=115200
monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep
lib_deps = lvgl/lvgl@9.3.0
board_build.psram_type = opi
board_build.flash_mode = qio
build_flags = -std=gnu++17
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_HAS_PSRAM
	-DWAVESHARE_LCD_4_3INCH
    -DLV_CONF_INCLUDE_SIMPLE
	-Iinclude
upload_port = COM15
monitor_port = COM15