// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#ifndef _WAVESHAREESP32_S3_4_3INCH_800X480_UI_H
#define _WAVESHAREESP32_S3_4_3INCH_800X480_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_scr_main.h"
#include "ui_scr_gauges1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_rpm_gauge3_png);    // assets/RPM Gauge3.png
LV_IMG_DECLARE(ui_img_gaugetest180b_png);    // assets/GaugeTest180b.png

// FONTS
LV_FONT_DECLARE(ui_font_JetBrainsMono34bpp4);
LV_FONT_DECLARE(ui_font_JetBrainsMonoReg48Bpp4);
LV_FONT_DECLARE(ui_font_JetBrainsMonoReg60Bpp4);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
