// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#ifndef _WAVESHAREESP32_S3_4_3INCH_800X480_UI_COMP_HOOK_H
#define _WAVESHAREESP32_S3_4_3INCH_800X480_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_MainGauge_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
