// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#ifndef _UI_COMP_MAINGAUGE_H
#define _UI_COMP_MAINGAUGE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT MainGauge
#define UI_COMP_MAINGAUGE_MAINGAUGE 0
#define UI_COMP_MAINGAUGE_MAIN_VAL1 1
#define UI_COMP_MAINGAUGE_MAIN_LABEL1 2
#define _UI_COMP_MAINGAUGE_NUM 3
lv_obj_t * ui_MainGauge_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
