// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveShareDisplay1

#include "ui.h"

void ui_comp_MainGauge_create_hook(lv_obj_t * comp)
{
}
