// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#include "ui.h"

// COMPONENT MainGauge

lv_obj_t * ui_MainGauge_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_MainGauge;
    cui_MainGauge = lv_arc_create(comp_parent);
    lv_obj_set_width(cui_MainGauge, 180);
    lv_obj_set_height(cui_MainGauge, 180);
    lv_obj_set_x(cui_MainGauge, -305);
    lv_obj_set_y(cui_MainGauge, -147);
    lv_obj_set_align(cui_MainGauge, LV_ALIGN_CENTER);
    lv_arc_set_range(cui_MainGauge, 0, 120);
    lv_arc_set_value(cui_MainGauge, 20);
    lv_obj_set_style_arc_rounded(cui_MainGauge, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(cui_MainGauge, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(cui_MainGauge, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(cui_MainGauge, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(cui_MainGauge, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_MainGauge, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_t * cui_Main_Val1;
    cui_Main_Val1 = lv_label_create(cui_MainGauge);
    lv_obj_set_width(cui_Main_Val1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Main_Val1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Main_Val1, 2);
    lv_obj_set_y(cui_Main_Val1, -5);
    lv_obj_set_align(cui_Main_Val1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Main_Val1, "27");
    lv_obj_set_style_text_color(cui_Main_Val1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Main_Val1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Main_Val1, &ui_font_JetBrainsMono34bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Main_Label1;
    cui_Main_Label1 = lv_label_create(cui_MainGauge);
    lv_obj_set_width(cui_Main_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Main_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Main_Label1, 2);
    lv_obj_set_y(cui_Main_Label1, 47);
    lv_obj_set_align(cui_Main_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Main_Label1, "LCB");
    lv_obj_set_style_text_color(cui_Main_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Main_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_Main_Label1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Main_Label1, &ui_font_JetBrainsMono34bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_MAINGAUGE_NUM);
    children[UI_COMP_MAINGAUGE_MAINGAUGE] = cui_MainGauge;
    children[UI_COMP_MAINGAUGE_MAIN_VAL1] = cui_Main_Val1;
    children[UI_COMP_MAINGAUGE_MAIN_LABEL1] = cui_Main_Label1;
    lv_obj_add_event_cb(cui_MainGauge, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_MainGauge, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_MainGauge_create_hook(cui_MainGauge);
    return cui_MainGauge;
}

