// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#include "ui.h"

lv_obj_t * ui_scr_main = NULL;
lv_obj_t * ui_scr_main_img_engine_rpm = NULL;
lv_obj_t * ui_scr_main_gau_engine_rpm = NULL;
lv_obj_t * ui_scr_main_lbl_engine_rpm_val = NULL;
// event funtions

// build funtions

void ui_scr_main_screen_init(void)
{
    ui_scr_main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scr_main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_scr_main, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_scr_main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_scr_main, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_main_img_engine_rpm = lv_image_create(ui_scr_main);
    lv_image_set_src(ui_scr_main_img_engine_rpm, &ui_img_rpm_gauge3_png);
    lv_obj_set_width(ui_scr_main_img_engine_rpm, LV_SIZE_CONTENT);   /// 434
    lv_obj_set_height(ui_scr_main_img_engine_rpm, LV_SIZE_CONTENT);    /// 433
    lv_obj_set_x(ui_scr_main_img_engine_rpm, 0);
    lv_obj_set_y(ui_scr_main_img_engine_rpm, -22);
    lv_obj_set_align(ui_scr_main_img_engine_rpm, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scr_main_img_engine_rpm, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_scr_main_img_engine_rpm, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scr_main_gau_engine_rpm = lv_arc_create(ui_scr_main);
    lv_obj_set_width(ui_scr_main_gau_engine_rpm, 385);
    lv_obj_set_height(ui_scr_main_gau_engine_rpm, 385);
    lv_obj_set_x(ui_scr_main_gau_engine_rpm, 0);
    lv_obj_set_y(ui_scr_main_gau_engine_rpm, -20);
    lv_obj_set_align(ui_scr_main_gau_engine_rpm, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_scr_main_gau_engine_rpm, 0, 8000);
    lv_arc_set_value(ui_scr_main_gau_engine_rpm, 4500);
    lv_arc_set_bg_angles(ui_scr_main_gau_engine_rpm, 149, 30);
    lv_obj_set_style_arc_color(ui_scr_main_gau_engine_rpm, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_main_gau_engine_rpm, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_scr_main_gau_engine_rpm, lv_color_hex(0x4040FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_main_gau_engine_rpm, 200, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_scr_main_gau_engine_rpm, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_scr_main_gau_engine_rpm, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scr_main_gau_engine_rpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_main_gau_engine_rpm, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_scr_main_lbl_engine_rpm_val = lv_label_create(ui_scr_main);
    lv_obj_set_width(ui_scr_main_lbl_engine_rpm_val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_main_lbl_engine_rpm_val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_scr_main_lbl_engine_rpm_val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_main_lbl_engine_rpm_val, "1234");
    lv_obj_set_style_text_color(ui_scr_main_lbl_engine_rpm_val, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_main_lbl_engine_rpm_val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_main_lbl_engine_rpm_val, &ui_font_JetBrainsMonoReg60Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_scr_main_screen_destroy(void)
{
    if(ui_scr_main) lv_obj_del(ui_scr_main);

    // NULL screen variables
    ui_scr_main = NULL;
    ui_scr_main_img_engine_rpm = NULL;
    ui_scr_main_gau_engine_rpm = NULL;
    ui_scr_main_lbl_engine_rpm_val = NULL;

}
