// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#ifndef UI_SCR_MAIN_H
#define UI_SCR_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_main
extern void ui_scr_main_screen_init(void);
extern void ui_scr_main_screen_destroy(void);
extern lv_obj_t * ui_scr_main;
extern lv_obj_t * ui_scr_main_img_engine_rpm;
extern lv_obj_t * ui_scr_main_gau_engine_rpm;
extern lv_obj_t * ui_scr_main_lbl_engine_rpm_val;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

