// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#include "ui.h"

lv_obj_t * ui_scr_gauges1 = NULL;
lv_obj_t * ui_scr_gauges1_Main_Arc3 = NULL;
lv_obj_t * ui_scr_gauges1_Main_Val3 = NULL;
lv_obj_t * ui_scr_gauges1_Main_Label3 = NULL;
lv_obj_t * ui_scr_gauges1_gau_cyl_head_l_temp = NULL;
lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_val = NULL;
lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_title = NULL;
lv_obj_t * ui_scr_gauges1_gau_cyl_head_l_temp1 = NULL;
lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_val1 = NULL;
lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_title1 = NULL;
// event funtions

// build funtions

void ui_scr_gauges1_screen_init(void)
{
    ui_scr_gauges1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_scr_gauges1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_scr_gauges1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_gauges1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_Main_Arc3 = lv_arc_create(ui_scr_gauges1);
    lv_obj_set_width(ui_scr_gauges1_Main_Arc3, 150);
    lv_obj_set_height(ui_scr_gauges1_Main_Arc3, 150);
    lv_obj_set_x(ui_scr_gauges1_Main_Arc3, 307);
    lv_obj_set_y(ui_scr_gauges1_Main_Arc3, 150);
    lv_obj_set_align(ui_scr_gauges1_Main_Arc3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_scr_gauges1_Main_Arc3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_arc_set_value(ui_scr_gauges1_Main_Arc3, 10);
    lv_obj_set_style_arc_rounded(ui_scr_gauges1_Main_Arc3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_Main_Val3 = lv_label_create(ui_scr_gauges1_Main_Arc3);
    lv_obj_set_width(ui_scr_gauges1_Main_Val3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_Main_Val3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_Main_Val3, 2);
    lv_obj_set_y(ui_scr_gauges1_Main_Val3, 0);
    lv_obj_set_align(ui_scr_gauges1_Main_Val3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_Main_Val3, "27");
    lv_obj_set_style_text_color(ui_scr_gauges1_Main_Val3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_Main_Val3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_Main_Val3, &ui_font_JetBrainsMono34bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_Main_Label3 = lv_label_create(ui_scr_gauges1_Main_Arc3);
    lv_obj_set_width(ui_scr_gauges1_Main_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_Main_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_Main_Label3, 3);
    lv_obj_set_y(ui_scr_gauges1_Main_Label3, 53);
    lv_obj_set_align(ui_scr_gauges1_Main_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_Main_Label3, "LCB");
    lv_obj_set_style_text_color(ui_scr_gauges1_Main_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_Main_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scr_gauges1_Main_Label3, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_Main_Label3, &ui_font_JetBrainsMono34bpp4, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_gau_cyl_head_l_temp = lv_arc_create(ui_scr_gauges1);
    lv_obj_set_width(ui_scr_gauges1_gau_cyl_head_l_temp, 180);
    lv_obj_set_height(ui_scr_gauges1_gau_cyl_head_l_temp, 180);
    lv_obj_set_x(ui_scr_gauges1_gau_cyl_head_l_temp, -300);
    lv_obj_set_y(ui_scr_gauges1_gau_cyl_head_l_temp, -146);
    lv_obj_set_align(ui_scr_gauges1_gau_cyl_head_l_temp, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_scr_gauges1_gau_cyl_head_l_temp, 40, 100);
    lv_arc_set_value(ui_scr_gauges1_gau_cyl_head_l_temp, 70);
    lv_arc_set_bg_angles(ui_scr_gauges1_gau_cyl_head_l_temp, 90, 0);
    lv_obj_set_style_arc_color(ui_scr_gauges1_gau_cyl_head_l_temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_gauges1_gau_cyl_head_l_temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_scr_gauges1_gau_cyl_head_l_temp, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_scr_gauges1_gau_cyl_head_l_temp, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_scr_gauges1_gau_cyl_head_l_temp, &ui_img_gaugetest180b_png,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_scr_gauges1_gau_cyl_head_l_temp, lv_color_hex(0x4040FF),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_gauges1_gau_cyl_head_l_temp, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_scr_gauges1_gau_cyl_head_l_temp, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scr_gauges1_gau_cyl_head_l_temp, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_gauges1_gau_cyl_head_l_temp, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_scr_gauges1_lbl_cyl_head_l_temp_val = lv_label_create(ui_scr_gauges1_gau_cyl_head_l_temp);
    lv_obj_set_width(ui_scr_gauges1_lbl_cyl_head_l_temp_val, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_lbl_cyl_head_l_temp_val, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_lbl_cyl_head_l_temp_val, 0);
    lv_obj_set_y(ui_scr_gauges1_lbl_cyl_head_l_temp_val, 2);
    lv_obj_set_align(ui_scr_gauges1_lbl_cyl_head_l_temp_val, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_lbl_cyl_head_l_temp_val, "68");
    lv_obj_set_style_text_color(ui_scr_gauges1_lbl_cyl_head_l_temp_val, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_lbl_cyl_head_l_temp_val, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_lbl_cyl_head_l_temp_val, &ui_font_JetBrainsMonoReg60Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_lbl_cyl_head_l_temp_title = lv_label_create(ui_scr_gauges1_gau_cyl_head_l_temp);
    lv_obj_set_width(ui_scr_gauges1_lbl_cyl_head_l_temp_title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_lbl_cyl_head_l_temp_title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_lbl_cyl_head_l_temp_title, 58);
    lv_obj_set_y(ui_scr_gauges1_lbl_cyl_head_l_temp_title, 58);
    lv_obj_set_align(ui_scr_gauges1_lbl_cyl_head_l_temp_title, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_lbl_cyl_head_l_temp_title, "  C\nCyl");
    lv_obj_set_style_text_color(ui_scr_gauges1_lbl_cyl_head_l_temp_title, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_lbl_cyl_head_l_temp_title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scr_gauges1_lbl_cyl_head_l_temp_title, LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_lbl_cyl_head_l_temp_title, &ui_font_JetBrainsMono34bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_gau_cyl_head_l_temp1 = lv_arc_create(ui_scr_gauges1);
    lv_obj_set_width(ui_scr_gauges1_gau_cyl_head_l_temp1, 180);
    lv_obj_set_height(ui_scr_gauges1_gau_cyl_head_l_temp1, 180);
    lv_obj_set_x(ui_scr_gauges1_gau_cyl_head_l_temp1, -102);
    lv_obj_set_y(ui_scr_gauges1_gau_cyl_head_l_temp1, -143);
    lv_obj_set_align(ui_scr_gauges1_gau_cyl_head_l_temp1, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_scr_gauges1_gau_cyl_head_l_temp1, 40, 100);
    lv_arc_set_value(ui_scr_gauges1_gau_cyl_head_l_temp1, 70);
    lv_arc_set_bg_angles(ui_scr_gauges1_gau_cyl_head_l_temp1, 90, 0);
    lv_obj_set_style_arc_color(ui_scr_gauges1_gau_cyl_head_l_temp1, lv_color_hex(0xFFFFFF),
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_gauges1_gau_cyl_head_l_temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_scr_gauges1_gau_cyl_head_l_temp1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_scr_gauges1_gau_cyl_head_l_temp1, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_image_src(ui_scr_gauges1_gau_cyl_head_l_temp1, &ui_img_gaugetest180b_png,
                                   LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_scr_gauges1_gau_cyl_head_l_temp1, lv_color_hex(0x4040FF),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_scr_gauges1_gau_cyl_head_l_temp1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_scr_gauges1_gau_cyl_head_l_temp1, false, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_scr_gauges1_gau_cyl_head_l_temp1, lv_color_hex(0x4040FF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_scr_gauges1_gau_cyl_head_l_temp1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_scr_gauges1_lbl_cyl_head_l_temp_val1 = lv_label_create(ui_scr_gauges1_gau_cyl_head_l_temp1);
    lv_obj_set_width(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, 0);
    lv_obj_set_y(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, 2);
    lv_obj_set_align(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, "636");
    lv_obj_set_style_text_color(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_lbl_cyl_head_l_temp_val1, &ui_font_JetBrainsMonoReg60Bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_scr_gauges1_lbl_cyl_head_l_temp_title1 = lv_label_create(ui_scr_gauges1_gau_cyl_head_l_temp1);
    lv_obj_set_width(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, 58);
    lv_obj_set_y(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, 58);
    lv_obj_set_align(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, "  C\nEGT");
    lv_obj_set_style_text_color(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, LV_TEXT_ALIGN_LEFT,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_scr_gauges1_lbl_cyl_head_l_temp_title1, &ui_font_JetBrainsMono34bpp4,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_scr_gauges1_screen_destroy(void)
{
    if(ui_scr_gauges1) lv_obj_del(ui_scr_gauges1);

    // NULL screen variables
    ui_scr_gauges1 = NULL;
    ui_scr_gauges1_Main_Arc3 = NULL;
    ui_scr_gauges1_Main_Val3 = NULL;
    ui_scr_gauges1_Main_Label3 = NULL;
    ui_scr_gauges1_gau_cyl_head_l_temp = NULL;
    ui_scr_gauges1_lbl_cyl_head_l_temp_val = NULL;
    ui_scr_gauges1_lbl_cyl_head_l_temp_title = NULL;
    ui_scr_gauges1_gau_cyl_head_l_temp1 = NULL;
    ui_scr_gauges1_lbl_cyl_head_l_temp_val1 = NULL;
    ui_scr_gauges1_lbl_cyl_head_l_temp_title1 = NULL;

}
