// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: WaveshareESP32-S3_4.3inch_800x480

#ifndef UI_SCR_GAUGES1_H
#define UI_SCR_GAUGES1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_scr_gauges1
extern void ui_scr_gauges1_screen_init(void);
extern void ui_scr_gauges1_screen_destroy(void);
extern lv_obj_t * ui_scr_gauges1;
extern lv_obj_t * ui_scr_gauges1_Main_Arc3;
extern lv_obj_t * ui_scr_gauges1_Main_Val3;
extern lv_obj_t * ui_scr_gauges1_Main_Label3;
extern lv_obj_t * ui_scr_gauges1_gau_cyl_head_l_temp;
extern lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_val;
extern lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_title;
extern lv_obj_t * ui_scr_gauges1_gau_cyl_head_l_temp1;
extern lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_val1;
extern lv_obj_t * ui_scr_gauges1_lbl_cyl_head_l_temp_title1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

